'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {LogOut,RefreshCw,BookOpen,Clock,ArrowUpRight} from 'lucide-react';
import {Brand,Notice,Loading,Empty,Footer} from '@/components/shared';
import {api,ApiError} from '@/lib/api';
import {Student,Classroom,Lesson,PictureGame,avatars} from '@/lib/types';
import Link from 'next/link';
type Data={student:Student;class:Classroom;lessons:Lesson[];games:PictureGame[];attempts:{game_id:string;score:number;completed_at:string|null}[]};
export default function StudentPage(){const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const router=useRouter();
 async function load(){setBusy(true);setError('');try{setData(await api<Data>('student-me',{},'student'))}catch(e){if(e instanceof ApiError&&(e.status===401||e.status===403)){sessionStorage.removeItem('eq_student');setData(null)}setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function logout(){try{await api('student-logout',{},'student')}finally{sessionStorage.removeItem('eq_student');router.push('/')}}
 return <div className="public-page"><header className="public-header"><Brand/><button className="button subtle" onClick={logout}><LogOut size={16}/> Sair</button></header><main className="student-main"><Notice message={error} error/>{!data&&busy?<Loading/>:!data?<Empty title="Vamos voltar para sua turma?"><a href="/">Entrar novamente</a></Empty>:<><div className="student-greeting"><div><div className="eyebrow">SEU ESPAÇO DE APRENDIZAGEM</div><h1>Hello, {data.student.display_name}<span className="red">!</span></h1><p className="muted">Uma descoberta de cada vez. Você está no lugar certo.</p></div><span className="profile-avatar">{avatars[data.student.avatar]}</span></div><div className="class-strip"><span><BookOpen size={20}/><strong>{data.class.name}</strong></span><span>{data.class.meeting_days.join(' e ')}</span><button className="text-link" onClick={load} disabled={busy}><RefreshCw size={16} className={busy?'spin':''}/>Atualizar</button></div>{data.student.status==='pending'?<section className="pending-card"><Clock size={36}/><h2>Seu lugar está quase pronto.</h2><p>A professora recebeu seu cadastro. Assim que ela aprovar, suas aulas aparecerão aqui.</p><small>Você pode atualizar esta página para conferir.</small></section>:<><div className="section-heading"><div><div className="eyebrow">VAMOS CONTINUAR APRENDENDO</div><h2>Suas aulas</h2></div><span className="pill">{data.lessons.length} disponíveis</span></div>{data.lessons.length===0?<Empty title="A próxima descoberta vem aí.">A professora ainda não liberou uma aula para sua turma. Volte no próximo encontro!</Empty>:<div className="lesson-grid">{data.lessons.map(l=><article className="lesson-card" key={l.id}><div className="lesson-card-top"><span className="icon-square"><BookOpen size={23}/></span><span className="date-label">{new Date(l.lesson_date+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}</span></div><small>{l.topic||'AULA DE INGLÊS'}</small><h3>{l.title}</h3><p>{l.objective||'Vamos explorar esse conteúdo juntos na aula.'}</p>{data.games.find(g=>g.lesson_id===l.id)?<Link className="button primary" href={`/play/${data.games.find(g=>g.lesson_id===l.id)!.id}`}>Jogar Picture Challenge <ArrowUpRight size={17}/></Link>:<div className="lesson-bottom">O jogo está sendo preparado <ArrowUpRight size={17}/></div>}{data.attempts.filter(a=>a.game_id===data.games.find(g=>g.lesson_id===l.id)?.id&&a.completed_at).length>0&&<small>Seu recorde: {Math.max(...data.attempts.filter(a=>a.game_id===data.games.find(g=>g.lesson_id===l.id)?.id&&a.completed_at).map(a=>a.score))} pontos</small>}</article>)}</div>}</> }</>}</main><Footer/></div>
}
