'use client';
import {useEffect,useState} from 'react';
import {Plus,Trash2,X} from 'lucide-react';
import {api} from '@/lib/api';
import {Lesson} from '@/lib/types';
import {Notice,Loading} from './shared';
type Item={image_url:string;answer:string;choices:string[]};
type EditorData={game:{title:string}|null;items:Item[];locked:boolean};
const rooms=['bathroom','bedroom','kitchen','living room','dining room','garage','backyard','laundry room'];
const roomImages=['bathroom','bedroom','kitchen','living-room','dining-room','garage','backyard','laundry-room'];
const starter:Item[]=[
 ...rooms.map((word,i)=>({image_url:`/rooms/${roomImages[i]}.svg`,answer:word,choices:[word,rooms[(i+2)%rooms.length],rooms[(i+4)%rooms.length],rooms[(i+6)%rooms.length]]})),
 {image_url:'/furniture/bed.svg',answer:'bed',choices:['closet','bed','sofa','lamp']},
 {image_url:'/furniture/fridge.svg',answer:'fridge',choices:['stove','fridge','dishwasher','washing machine']},
 {image_url:'/furniture/sofa.svg',answer:'sofa',choices:['bed','sofa','sink','TV stand']},
 {image_url:'/furniture/washing-machine.svg',answer:'washing machine',choices:['fridge','microwave oven','washing machine','dishwasher']},
];
export function GameEditor({lesson,onClose,onSaved}:{lesson:Lesson;onClose:()=>void;onSaved:()=>void}){
 const [items,setItems]=useState<Item[]>(starter);const [title,setTitle]=useState('Picture Challenge');const [locked,setLocked]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{let active=true;api<EditorData>('game-editor',{lesson_id:lesson.id}).then(d=>{if(active){if(d.game){setTitle(d.game.title);setItems(d.items)}setLocked(d.locked)}}).catch(e=>{if(active)setMessage((e as Error).message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[lesson.id]);
 function change(i:number,field:'image_url'|'answer'|'choice',value:string,n=0){setItems(old=>old.map((item,index)=>index!==i?item:field==='choice'?{...item,choices:item.choices.map((c,j)=>j===n?value:c)}:{...item,[field]:value}))}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage('');try{await api('save-game',{lesson_id:lesson.id,title,items});onSaved();onClose()}catch(e){setMessage((e as Error).message)}finally{setSaving(false)}}
 return <div className="game-editor-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="game-editor" role="dialog" aria-modal="true" aria-label="Editar Picture Challenge"><header className="game-editor-head"><div><span className="eyebrow">JOGO DA AULA · {lesson.title}</span><h2>Picture Challenge</h2><p>Uma imagem, quatro palavras. O aluno escolhe qual palavra combina com a imagem.</p></div><button className="icon-button" aria-label="Fechar" onClick={onClose}><X/></button></header><Notice message={message} error/>{loading?<Loading/>:<form onSubmit={save}><label>Nome do jogo<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={80} required disabled={locked}/></label><p className="fine-print">Use 4 a 12 imagens. Para cada uma, escreva a resposta correta exatamente igual a uma das quatro opções. Você pode usar um endereço HTTPS ou uma imagem desta biblioteca. Depois que um aluno começar, as perguntas ficam fixas para preservar as pontuações.</p><div className="game-editor-list">{items.map((item,i)=><fieldset className="editor-item" key={i} disabled={locked}><legend>Imagem {i+1}</legend><div className="editor-item-main"><img src={item.image_url} alt="Prévia da questão" onError={e=>{e.currentTarget.style.visibility='hidden'}} onLoad={e=>{e.currentTarget.style.visibility='visible'}}/><div><label>Endereço da imagem<input value={item.image_url} onChange={e=>change(i,'image_url',e.target.value)} required/></label><label>Resposta certa<input value={item.answer} onChange={e=>change(i,'answer',e.target.value)} required maxLength={60}/></label></div></div><div className="editor-choices">{item.choices.map((choice,j)=><label key={j}>Opção {j+1}<input value={choice} onChange={e=>change(i,'choice',e.target.value,j)} required maxLength={60}/></label>)}</div>{!locked&&<button type="button" className="text-link" onClick={()=>setItems(old=>old.filter((_,index)=>index!==i))} disabled={items.length<=4}><Trash2 size={15}/>Remover imagem</button>}</fieldset>)}</div><div className="game-editor-footer">{locked?<span>Este jogo já recebeu respostas e não pode ser alterado.</span>:<><button type="button" className="button secondary" disabled={items.length>=12} onClick={()=>setItems(old=>[...old,{image_url:'/rooms/bathroom.svg',answer:'bathroom',choices:['bathroom','bedroom','kitchen','backyard']}])}><Plus size={16}/>Adicionar imagem</button><button className="button primary" disabled={saving}>{saving?'Salvando…':'Salvar jogo'}</button></>}</div></form>}</section></div>
}
