'use client';
import {useCallback,useEffect,useState,use} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,RotateCcw,Star} from 'lucide-react';
import {api} from '@/lib/api';
import {Brand,Notice,Loading} from '@/components/shared';
import {GameChoices,QuestionAudio} from '@/components/game-choices';
type Item={id:string;position:number;image_url:string;choices:string[]};
type Answer={item_id:string;correct:boolean;resolved:boolean;mistakes:number;points:number};
type State={game:{id:string;title:string};items:Item[];attempt:{id:string;score:number;attempt_number:number}|null;answers:Answer[];best:number;attemptsUsed:number};
type Feedback={correct:boolean;resolved:boolean;answer:string|null;mistakes:number;points:number;score:number;completed:boolean};
export default function Play({params}:{params:Promise<{id:string}>}){
 const {id}=use(params);const [data,setData]=useState<State|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [feedback,setFeedback]=useState<Feedback|null>(null);const [position,setPosition]=useState(0);
 const load=useCallback(async()=>{try{setData(await api<State>('game-state',{game_id:id},'student'));setError('')}catch(e){setError((e as Error).message)}},[id]);
 useEffect(()=>{void load()},[load]);
 async function start(){setBusy(true);setError('');try{await api('game-start',{game_id:id},'student');setPosition(0);setFeedback(null);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const resolved=data?.answers.filter(a=>a.resolved).length||0;
 const currentIndex=feedback?.resolved?position:Math.max(position,resolved);
 const item=data?.items[currentIndex];
 const finished=!!data&&!!data.attempt&&resolved===data.items.length;
 async function choose(choice:string){if(!item||busy||feedback?.resolved)return;setBusy(true);setError('');try{const response=await api<Feedback>('game-answer',{game_id:id,item_id:item.id,choice},'student');setFeedback(response);await load()}catch(e){setError((e as Error).message);await load()}finally{setBusy(false)}}
 function next(){setFeedback(null);setPosition(currentIndex+1)}
 return <div className="game-page"><header className="game-header"><Brand/><Link href="/student" className="button subtle"><ArrowLeft size={17}/> Minhas aulas</Link></header><main className="game-shell"><Notice message={error} error/>{!data&&!error?<Loading/>:data?<><div className="game-banner"><span className="eyebrow">ENGLISH QUEST · PICTURE CHALLENGE</span><h1>{data.game.title}</h1><p>Observe a imagem e escolha a palavra certa em inglês!</p><div className="game-metrics"><span><Star size={16}/>Recorde: {data.best} pontos</span><span>{data.attempt?`Tentativa ${data.attempt.attempt_number} de 3`:`${data.attemptsUsed} de 3 tentativas usadas`}</span></div></div>{!data.attempt?<section className="game-result"><span className="game-result-icon">🎯</span><h2>{data.attemptsUsed?'Vamos jogar mais uma vez?':'Prepare-se para descobrir!'}</h2><p>Você tem até três chances em cada imagem. Cada partida tem {data.items.length} imagens. Seu melhor resultado fica salvo.</p><button className="button primary" onClick={start} disabled={busy||data.attemptsUsed>=3}>{data.attemptsUsed>=3?'Suas tentativas terminaram':busy?'Preparando…':'Começar a jogar'} <ArrowRight size={18}/></button></section>:finished?<section className="game-result"><span className="game-result-icon">🏆</span><h2>Parabéns! Você terminou!</h2><strong>{data.attempt.score} pontos</strong><p>Seu recorde: {Math.max(data.best,data.attempt.score)} pontos.</p><button className="button primary" onClick={start} disabled={busy||data.attemptsUsed>=3}><RotateCcw size={17}/>Jogar outra vez</button><Link href="/student" className="button secondary">Voltar para minhas aulas</Link></section>:item?<section className="game-board"><div className="game-progress"><strong>Imagem {currentIndex+1} de {data.items.length}</strong><strong>{feedback?.score??data.attempt.score} pontos</strong></div><div className="game-track"><span style={{width:`${(currentIndex/data.items.length)*100}%`}}/></div><div className="game-picture"><img src={item.image_url} alt="Imagem da questão: identifique a palavra correta"/></div><h2>What is this? <QuestionAudio/></h2><p>Toque na palavra que combina com a imagem.</p><GameChoices choices={item.choices} disabled={busy||!!feedback?.resolved} onChoose={choose}/>{feedback&&<div role="status" className={`game-feedback ${feedback.correct?'good':'retry'}`}><strong>{feedback.correct?'Muito bem! ✨':feedback.resolved?'A resposta era '+feedback.answer+'.':'Tente novamente! Você consegue.'}</strong><span>{feedback.points>0?`+${feedback.points} pontos`:feedback.resolved?'Vamos para a próxima imagem.':`${3-feedback.mistakes} chances restantes`}</span>{feedback.resolved&&<button className="button primary" onClick={async()=>{next();if(feedback.completed)await load()}}>{feedback.completed?'Ver meu resultado':'Próxima imagem'}<ArrowRight size={16}/></button>}</div>}</section>:null}</>:null}</main></div>
}
